kind: pipeline
name: default
type: docker

steps:
  - name: base
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: docker_password
      repo: rg.fr-par.scw.cloud/jlelse/goblog
      registry: rg.fr-par.scw.cloud/jlelse
      tags: latest
  - name: tools
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: docker_password
      repo: rg.fr-par.scw.cloud/jlelse/goblog
      registry: rg.fr-par.scw.cloud/jlelse
      tags: tools
      dockerfile: Dockerfile.Tools

trigger:
  branch:
    - master
  event:
    - push