kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - sleep 5 # give docker enough time to start
      - echo $DOCKER_PASSWORD | docker login --username nologin --password-stdin rg.fr-par.scw.cloud/jlelse
      - DOCKER_BUILDKIT=1 docker build -t rg.fr-par.scw.cloud/jlelse/goblog:latest . --target base
      - DOCKER_BUILDKIT=1 docker build -t rg.fr-par.scw.cloud/jlelse/goblog:tools . --target tools
      - docker push --all-tags rg.fr-par.scw.cloud/jlelse/goblog

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}

trigger:
  branch:
    - master
  event:
    - push
