kind: pipeline
name: default

steps:
  - name: publish
    image: plugins/docker
    settings:
      username: nologin
      password:
        from_secret: docker_password
      repo: rg.fr-par.scw.cloud/jlelse/goblog
      registry: rg.fr-par.scw.cloud/jlelse
      tags: latest
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request