run:
  timeout: 5m
  issue-exit-code: 0
  skip-tests: true
  build-tags:
    - linux
    - libsqlite3
    - sqlite_fts5
linters:
  enable:
    # Default linters
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Other linters
    - dupl
    - gofmt
    - bodyclose
    - noctx
    - prealloc
    - unparam
    - durationcheck
    - bidichk
    - containedctx
    - contextcheck
    - gosec
linters-settings:
  gosimple:
    go: "1.18"
    checks: ["all"]
  gostatichcheck:
    go: "1.18"
    checks: ["all"]
  dupl:
    threshold: 125