server:
  logging: false
  port: 8080
  domain: example.com
  publicHttps: false
  letsEncryptMail: mail@example.com
  localHttps: false
database:
  file: data/db.sqlite
cache:
  enable: true
  expiration: 600
blog:
  lang: en
  title: My blog
  sections:
    - posts
  taxonomies:
    - tags
user:
  nick: admin
  name: Admin
  password: secret