server:
  logging: false
  port: 8080
  domain: example.com
  publicHttps: false
  letsEncryptMail: mail@example.com
  localHttps: false
database:
  file: data/db.sqlite
cache:
  enable: true
  expiration: 600
blog:
  lang: en
  title: My blog
  description: This is my blog
  sections:
    - name: posts
      title: Posts
      description: "**Posts** on this blog"
  taxonomies:
    - name: tags
      title: Tags
      description: "**Tags** on this blog"
user:
  nick: admin
  name: Admin
  password: secret