server:
  logging: false
  port: 8080
  domain: example.com
  publicAdress: http://localhost:8080
  publicHttps: false
  letsEncryptMail: mail@example.com
  localHttps: false
database:
  file: data/db.sqlite
cache:
  enable: true
  expiration: 600
blog:
  lang: en
  title: My blog
  description: This is my blog
  sections:
    - name: posts
      title: Posts
      description: "**Posts** on this blog"
  taxonomies:
    - name: tags
      title: Tags
      description: "**Tags** on this blog"
  menus:
    main:
      items:
        - title: Home
          link: /
        - title: Posts
          link: /posts
  photos:
    enable: true
    parameter: images
    path: /photos
    title: Photos
    description: "Photos on this blog"
  activitystreams:
    enable: true
    replyParameter: replylink
    imagesParameter: images
user:
  nick: admin
  name: Admin
  password: secret
hugo:
  frontmatter:
    - meta: title
      parameter: title
    - meta: tags
      parameter: tags