acommentby: "A comment by"
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
captcha: "Captcha"
captchainstructions: "Please enter the digits from the image above"
chars: "Characters"
comment: "Comment"
comments: "Comments"
confirmdelete: "Confirm deletion"
connectedviator: "Connected via Tor."
connectviator: "Connect via Tor."
create: "Create"
delete: "Delete"
docomment: "Comment"
download: "Download"
drafts: "Drafts"
editor: "Editor"
feed: "Feed"
fileuses: "file uses"
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
likeof: "Like of"
loading: "Loading..."
location: "Location"
locationfailed: "Failed to request the location"
locationget: "Request location"
locationnotsupported: "The location API is not supported by this browser"
login: "Login"
logout: "Logout"
mediafiles: "Media files"
nameopt: "Name (optional)"
next: "Next"
nofiles: "No files"
nolocations: "No posts with locations"
noposts: "There are no posts here."
notifications: "Notifications"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
password: "Password"
pinned: "Pinned"
posts: "Posts"
prev: "Previous"
privateposts: "Private posts"
publishedon: "Published on"
replyto: "Reply to"
reverify: "Reverify"
scopes: "Scopes"
search: "Search"
send: "Send (to review)"
share: "Share online"
shorturl: "Short link:"
speak: "Read aloud"
stopspeak: "Stop reading aloud"
submit: "Submit"
total: "Total"
totp: "TOTP"
translate: "Translate"
translations: "Translations"
unlistedposts: "Unlisted posts"
update: "Update"
updatedon: "Updated on"
upload: "Upload"
username: "Username"
verified: "Verified"
view: "View"
webmentions: "Webmentions"
websiteopt: "Website (optional)"
whatistor: "What is Tor?"
withoutdate: "Without date"
words: "Words"
wordsperpost: "Words per post"
year: "Year"