publishedon: "Published on"
updatedon: "Updated on"
next: "Next"
prev: "Previous"
view: "View"
authenticate: "Authenticate"
scopes: "Scopes"
indieauth: "IndieAuth"
replyto: "Reply to"
likeof: "Like of"
translations: "Translations"
share: "Share"
speak: "Read to me, please."
stopspeak: "Stop speaking!"