anoncomment: "You can also create an anonymous comment."
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
count: "Count"
create: "Create"
delete: "Delete"
drafts: "Drafts"
editor: "Editor"
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
likeof: "Like of"
login: "Login"
next: "Next"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
password: "Password"
prev: "Previous"
publishedon: "Published on"
replyto: "Reply to"
scopes: "Scopes"
search: "Search"
send: "Send (to review)"
share: "Share"
shorturl: "Short link:"
speak: "Read to me, please."
stopspeak: "Stop speaking!"
total: "Total"
translations: "Translations"
update: "Update"
updatedon: "Updated on"
upload: "Upload"
username: "Username"
verified: "Verified"
view: "View"
webmentions: "Webmentions"
year: "Year"