acommentby: "A comment by"
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
captchainstructions: "Please enter the digits from the image above"
chars: "Characters"
comment: "Comment"
comments: "Comments"
confirmdelete: "Confirm deletion"
connectedviator: "Connected via Tor."
connectviator: "Connect via Tor."
contactagreesend: "Accept & Send"
contactsend: "Send"
create: "Create"
delete: "Delete"
deletedposts: "Deleted posts"
deletedpostsdesc: "Deleted posts that will be permanently deleted after 7 days."
docomment: "Comment"
download: "Download"
drafts: "Drafts"
draftsdesc: "Posts with status `draft`."
editor: "Editor"
editorpostdesc: "💡 Empty parameters are removed automatically. More possible parameters: %s. Possible states for `%s`: %s."
emailopt: "Email (optional)"
feed: "Feed"
fileuses: "file uses"
gentts: "Generate Text-To-Speech audio"
gpxhelper: "GPX helper"
gpxhelperdesc: "💡 Minify GPX and generate YAML for the frontmatter."
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
kilometers: "kilometers"
likeof: "Like of"
loading: "Loading..."
location: "Location"
locationfailed: "Failed to request the location"
locationget: "Request location"
locationnotsupported: "The location API is not supported by this browser"
login: "Login"
logout: "Logout"
mediafiles: "Media files"
message: "Message"
messagesent: "Message sent"
nameopt: "Name (optional)"
next: "Next"
nofiles: "No files"
nolocations: "No posts with locations"
noposts: "There are no posts here."
notifications: "Notifications"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
password: "Password"
pinned: "Pinned"
posts: "Posts"
prev: "Previous"
privateposts: "Private posts"
privatepostsdesc: "Posts with status `private` that are visible only when logged in."
publishedon: "Published on"
replyto: "Reply to"
reverify: "Reverify"
scheduledposts: "Scheduled posts"
scheduledpostsdesc: "Posts with status `scheduled` that are published when the `published` date is reached."
scopes: "Scopes"
search: "Search"
send: "Send (to review)"
share: "Share online"
shorturl: "Short link:"
speak: "Read aloud"
status: "Status"
stopspeak: "Stop reading aloud"
submit: "Submit"
total: "Total"
totp: "TOTP"
translate: "Translate"
translations: "Translations"
undelete: "Undelete"
unlistedposts: "Unlisted posts"
unlistedpostsdesc: "Posts with status `unlisted` that are not displayed in archives."
update: "Update"
updatedon: "Updated on"
upload: "Upload"
username: "Username"
verified: "Verified"
view: "View"
webmentions: "Webmentions"
websiteopt: "Website (optional)"
whatistor: "What is Tor?"
withoutdate: "Without date"
words: "Words"
wordsperpost: "Words per post"
year: "Year"