acommentby: "A comment by"
approve: "Approve"
approved: "Approved"
authenticate: "Authenticate"
captcha: "Captcha"
captchainstructions: "Please enter the digits from the image above"
chars: "Characters"
comment: "Comment"
comments: "Comments"
confirmdelete: "Confirm deletion"
create: "Create"
delete: "Delete"
docomment: "Comment"
drafts: "Drafts"
editor: "Editor"
indieauth: "IndieAuth"
interactions: "Interactions & Comments"
interactionslabel: "Have you published a response to this? Paste the URL here."
likeof: "Like of"
login: "Login"
logout: "Logout"
nameopt: "Name (optional)"
next: "Next"
noposts: "There are no posts here."
notifications: "Notifications"
oldcontent: "⚠️ This entry is already over one year old. It may no longer be up to date. Opinions may have changed."
password: "Password"
posts: "Posts"
prev: "Previous"
publishedon: "Published on"
replyto: "Reply to"
scopes: "Scopes"
search: "Search"
send: "Send (to review)"
share: "Share online"
shorturl: "Short link:"
speak: "Read aloud"
stopspeak: "Stop reading aloud"
submit: "Submit"
total: "Total"
totp: "TOTP"
translate: "Translate"
translations: "Translations"
update: "Update"
updatedon: "Updated on"
upload: "Upload"
username: "Username"
verified: "Verified"
view: "View"
webmentions: "Webmentions"
websiteopt: "Website (optional)"
withoutdate: "Without date"
words: "Words"
wordsperpost: "Words per post"
year: "Year"