name: Lint Code with golangci-lint

on:
  push:
    branches: [ master ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Checkout
      uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest